"""008_phase8_hardening

Revision ID: 8c645b0be11f
Revises: 007_phase7_documents
Create Date: 2026-02-12 10:11:36.250597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c645b0be11f'
down_revision = '007_phase7_documents'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create activity_logs table
    op.create_table('activity_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=False),
        sa.Column('performed_by_user_id', sa.UUID(), nullable=False),
        sa.Column('old_value', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('new_value', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_performed_by_user_id'), 'activity_logs', ['performed_by_user_id'], unique=False)

    # Add performance indexes for other tables
    # Tasks
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_urgency_label', 'tasks', ['urgency_label'], unique=False)
    op.create_index('ix_tasks_assigned_user_id', 'tasks', ['assigned_user_id'], unique=False)
    op.create_index('ix_tasks_assigned_team_id', 'tasks', ['assigned_team_id'], unique=False)
    op.create_index('ix_tasks_owner_user_id', 'tasks', ['owner_user_id'], unique=False)

    # Projects
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_project_manager_user_id', 'projects', ['project_manager_user_id'], unique=False)
    op.create_index('ix_projects_owner_user_id', 'projects', ['owner_user_id'], unique=False)

    # Events
    op.create_index('ix_events_event_datetime', 'events', ['event_datetime'], unique=False)

    # Documents
    op.create_index('ix_documents_uploaded_by_user_id', 'documents', ['uploaded_by_user_id'], unique=False)

    # Existing auto-generated ops...
    # op.drop_constraint('auth_refresh_tokens_token_key', 'auth_refresh_tokens', type_='unique')
    # op.drop_index('ix_auth_refresh_tokens_token', table_name='auth_refresh_tokens')
    # op.create_index(op.f('ix_auth_refresh_tokens_token'), 'auth_refresh_tokens', ['token'], unique=True)
    # op.drop_constraint('pages_key_key', 'pages', type_='unique')
    # op.drop_index('ix_pages_key', table_name='pages')
    # op.create_index(op.f('ix_pages_key'), 'pages', ['key'], unique=True)
    # op.drop_index('ix_users_manager_id', table_name='users')
    # op.drop_constraint('users_email_key', 'users', type_='unique')
    # op.drop_constraint('users_username_key', 'users', type_='unique')
    # op.drop_index('ix_users_email', table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.drop_index('ix_users_username', table_name='users')
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop activity_logs and indexes
    op.drop_index('ix_documents_uploaded_by_user_id', table_name='documents')
    op.drop_index('ix_events_event_datetime', table_name='events')
    op.drop_index('ix_projects_owner_user_id', table_name='projects')
    op.drop_index('ix_projects_project_manager_user_id', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_tasks_owner_user_id', table_name='tasks')
    op.drop_index('ix_tasks_assigned_team_id', table_name='tasks')
    op.drop_index('ix_tasks_assigned_user_id', table_name='tasks')
    op.drop_index('ix_tasks_urgency_label', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    
    op.drop_index(op.f('ix_activity_logs_performed_by_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')

    # Existing auto-generated downgrades...
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.drop_index(op.f('ix_pages_key'), table_name='pages')
    op.create_index('ix_pages_key', 'pages', ['key'], unique=False)
    op.create_unique_constraint('pages_key_key', 'pages', ['key'])
    op.drop_index(op.f('ix_auth_refresh_tokens_token'), table_name='auth_refresh_tokens')
    op.create_index('ix_auth_refresh_tokens_token', 'auth_refresh_tokens', ['token'], unique=False)
    op.create_unique_constraint('auth_refresh_tokens_token_key', 'auth_refresh_tokens', ['token'])
    # ### end Alembic commands ###
